CREATE TABLE ROBO_UNIT (
  ID BIGINT PRIMARY KEY,
  CREATED_ON TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NOT NULL,
  UID VARCHAR(255) NOT NULL,
  CONFIG VARCHAR(255) NOT NULL,
  UNITS BIGINT REFERENCES ROBO_UNIT(ID),
  PARENT_ID BIGINT
);

create sequence robo_unit_sequence start with 1 increment by 1;

CREATE TABLE ROBO_POINT (
  ID BIGINT primary key,
  CREATED_ON TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NOT NULL,
  UNIT BIGINT REFERENCES ROBO_UNIT(ID),
  VALUE_TYPE VARCHAR (255) NOT NULL,
  VALUES VARCHAR (255) NOT NULL
);

create sequence robo_unit_point_sequence start with 1 increment by 1;

ALTER TABLE ROBO_UNIT ADD COLUMN points BIGINT;
ALTER TABLE ROBO_UNIT ADD FOREIGN KEY (points) REFERENCES ROBO_POINT (id);