{
 "title": "Robo4j-Arm-Gripper dashboard",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "JVM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(robo4j_system_name_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(robo4j_system_name_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_committed_bytes{job=\"$job\", instance=\"$instance\"},pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_max_bytes,area)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_runtime_info{job=\"$job\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Robo4j System",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robo4j_system_name_info{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Robo4j-Pool-Size-Worker",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robo4j_pool_size_worker{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Robo4j-Pool-Size-Blocking",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robo4j_pool_size_blocking{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Robo4j-Pool-Size-Scheduler",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robo4j_pool_size_scheduler{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Robo4j Servos",
   "type": "timeseries",
   "description": "how much memory a process is consuming in physical RAM",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "robo4j_arm_servo1{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "robo4j_arm_servo3{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "robo4j_arm_servo4{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "robo4j_arm_servo5{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "robo4j_arm_servo6{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "robo4j_arm_servo7{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "description": "process_cpu_seconds_total Total user and system CPU time spent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    }
   ]
  },
  {
   "title": "Resident Set Size memory",
   "type": "timeseries",
   "description": "how much memory a process is consuming in physical RAM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    }
   ]
  },
  {
   "title": "Resident Set Size memory",
   "type": "timeseries",
   "description": "how much memory a process is consuming in physical RAM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "timeseries",
   "description": "jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Class loaded current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Memory Area [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_used_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory Pool Area [$mempool]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  }
 ]
}