name: robo4j-build-actions
run-name: ${{ github.actor }} is robo4j runner
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/45_github_actions'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'
      - name: Run build
        run: mvn clean install