name: robo4j-build-actions
run-name: ${{ github.actor }} is robo4j runner
on: [push]
jobs:
  robo4j-install:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/45_github_actions'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'correto'
          java-version: '11'
          cache: 'maven'
      - name: Run install
        run: mvn clean install